baseurl: ''
permalink: pretty
markdown: rdiscount
port: 3200
host: 127.0.0.1
about: "Suspendisse feugiat. Vivamus laoreet. Etiam sollicitudin, ipsum eu pulvinar rutrum, tellus ipsum laoreet sapien, quis venenatis ante odio sit amet eros. Proin viverra, ligula sit amet ultrices semper, ligula arcu tristique sapien, a accumsan nisi mauris ac eros. Aenean viverra rhoncus pede."
paypal:
  email: clevelandtapes@yahoo.com
prose:
  rooturl: '_posts'
  siteurl: 'https://guidetokulchur.github.io/'
  relativeLinks: 'https://guidetokulchur.github.io/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "hidden"
          value: "title"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
    _posts/title:
      - name: "category"
        field:
          element: "hidden"
          value: "title"
      - name: "layout"
        field:
          element: "hidden"
          value: "title"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "cover"
        field:
          element: "text"
          label: "Cover Image path"
          placeholder: "blah.jpg"
          help: "Upload an image using the WYSIWYG, or refer to an image in media/ folder. media/ prefix is assumed. Make sure it is optimized fo a full bleed, similar to a facebook cover photo (the crop will always be centered though)"
      - name: "description"
        field:
          element: "textarea"
          label: "Short Description"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author Name"
          placeholder: "James Baldwin"
      - name: "authorbio"
        field:
          element: "textarea"
          label: "Author Bio"
          placeholder: "Stuff"
      - name: "price"
        field:
          element: "text"
          label: "Price"
          placeholder: "30.00"
          help: "Be sure to leave out the $ sign!"
      - name: "releasedate"
        field:
          element: "datefield"
          label: "Release Date"
      - name: "instock"
        field:
          element: boolean
          label: "In Stock?"
      - name: "collection"
        field:
          element: "select"
          label: "Collection - Series or Journal"
          options:
            - name: "Dialogues Series"
              value: "dialogues-series"
            - name: "Dialogues Annual"
              value: "dialogues-annual"
            - name: "GTK Creative Journal"
              value: "gtk-creative-journal"
            - name: "Vanguard Series"
              value: "vanguard-series"
    _posts/collection:
      - name: "category"
        field:
          element: "hidden"
          value: "collection"
      - name: "layout"
        field:
          element: "hidden"
          value: "collection"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "cover"
        field:
          element: "text"
          label: "Cover Image path"
          placeholder: "blah.jpg"
          help: "Upload an image using the WYSIWYG, or refer to an image in media/ folder. media/ prefix is assumed. Make sure it is optimized fo a full bleed, similar to a facebook cover photo (the crop will always be centered though)"
      - name: "description"
        field:
          element: "textarea"
          label: "Short Description"
          value: ""
      - name: "collectiontype"
        field:
          label: "Collection Type"
          element: 'select'
          options:
            - name: 'Journal'
              value: 'journal'
            - name: 'Series'
              value: 'series'
    _posts/static:
      - name: "category"
        field:
          element: "hidden"
          value: "static"
      - name: "layout"
        field:
          element: "hidden"
          value: "static"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
