baseurl: /press
permalink: pretty
markdown: rdiscount
port: 3200
host: 127.0.0.1
about: "Suspendisse feugiat. Vivamus laoreet. Etiam sollicitudin, ipsum eu pulvinar rutrum, tellus ipsum laoreet sapien, quis venenatis ante odio sit amet eros. Proin viverra, ligula sit amet ultrices semper, ligula arcu tristique sapien, a accumsan nisi mauris ac eros. Aenean viverra rhoncus pede."
prose:
  rooturl: ''
  siteurl: 'http://guidetokulchur.github.io/press/'
  relativeLinks: 'http://guidetokulchur.github.io/press/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"
    _posts/title:
      - name: "category"
        field:
          element: "hidden"
          value: "title"
      - name: "layout"
        field:
          element: "hidden"
          value: "title"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "description"
        field:
          element: "textarea"
          label: "Short Description"
          value: ""
    _posts/collection:
      - name: "category"
        field:
          element: "hidden"
          value: "collection"
      - name: "layout"
        field:
          element: "hidden"
          value: "collection"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "description"
        field:
          element: "textarea"
          label: "Short Description"
          value: ""
      - name: "collectiontype"
        field:
          label: "Collection Type"
          element: 'select'
          options:
            - name: 'Journal'
              value: 'journal'
            - name: 'Series'
              value: 'series'
